# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import government_audit.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateField()),
                ('title', models.CharField(max_length=1024)),
                ('source', models.CharField(choices=[('AO', 'archive.org')], max_length=2)),
                ('external_identifier', models.CharField(max_length=256)),
                ('lexemes', government_audit.models.LexemesField(null=True)),
                ('text', models.TextField(default='')),
            ],
        ),
    ]
