# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('government_audit', '0002_auditdocument_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamedEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('frequency', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='government_audit.AuditDocument')),
            ],
        ),
    ]
