# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government_audit', '0004_auto_20171016_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditdocument',
            name='path',
            field=models.CharField(default='', max_length=256),
        ),
    ]
