# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-04 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('government_audit', '0005_auditdocument_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditdocument',
            name='url_active',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='namedentity',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='named_entities', to='government_audit.AuditDocument'),
        ),
    ]
