# Generated by Django 2.0.4 on 2018-08-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government_audit', '0007_auto_20180204_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditdocument',
            name='url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
