version: '2' # AWS only supports up to v2

services:
  db:
    image: postgres
  web:
  # AWS does not support the build directive.
  # You must do a 'docker build -t website . --build-arg django_secret_key='<your secret key>' first
    image: website
    ports:
      - "80:80"
    depends_on:
      - db