# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('time_taken', models.TimeField(auto_now_add=True)),
                ('geo_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('geo_lon', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
