# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('time_taken',)},
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
