# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 21:27
from __future__ import unicode_literals

from django.core.management import call_command
from django.db import migrations


fixture = 'initial_data'


def load_fixture(apps, schema_editor):
    call_command('loaddata', fixture, app_label='weblog')


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
